(function(g){var window=this;var qAa=function(a,b,c,d){var e=b.Xb();g.U(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.bd(c,d?d:"mqdefault.jpg");var k=b instanceof g.vO?g.RV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.uQ(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.vO?b.ya:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,aria_label:b.Pk||g.V("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.rl(c),is_live:m,
is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.wQ&&(c.playlist_length=b.getLength());a.update(c)},e6=function(a,b){g.rH.call(this,{G:"div",
da:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.created=!1},f6=function(a){g.W.call(this,{G:"div",
L:"ytp-upnext",P:{"aria-label":"{{aria_label}}"},N:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",P:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",N:[{G:"span",L:"ytp-upnext-header",aa:"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},{G:"span",L:"ytp-upnext-title",aa:"{{title}}"},{G:"span",L:"ytp-upnext-author",aa:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",P:{role:"button",href:"{{url}}","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
N:[{G:"svg",P:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},N:[{G:"circle",L:"ytp-svg-autoplay-circle",P:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",P:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",P:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",
N:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",aa:"\u0410\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043f\u0440\u0438\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e."}]}]});this.B=null;var b=this.g["ytp-upnext-cancel"];this.B=new g.W({G:"button",da:["ytp-upnext-cancel-button","ytp-button"],P:{tabindex:"0","aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},
aa:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.N(this,this.B);this.B.U("click",this.qQ,this);this.B.ua(b);this.o=a;this.J=this.g["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.H=new g.Yt(this.En,5E3,this);g.N(this,this.H);this.I=0;this.O(this.g["ytp-upnext-autoplay-icon"],"click",this.zS);this.oC();this.O(a,"autonavvisibility",this.oC);this.O(a,"mdxnowautoplaying",this.PR);this.O(a,"mdxautoplaycanceled",this.QR);this.O(a,"mdxautoplayupnext",this.TE);3==this.o.Ra()&&(a=(a=g.$U(g.VU(this.o)))?
a.pJ():null)&&this.TE(a)},rAa=function(a,b){a.C=b;
qAa(a,b,g.Y(a.o),"hqdefault.jpg")},g6=function(a,b){if(!a.A){g.XF("a11y-announce","\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 "+a.C.title);
a.I=g.hG();a.A=new g.Yt((0,g.A)(a.dr,a,b),25);a.dr(b);var c=b||g.Y(a.o).experiments.l("autoplay_time")||1E4;a.o.va("onAutonavCoundownStarted",c)}g.lq(a.element,"ytp-upnext-autoplay-paused")},i6=function(a){h6(a);
a.I=g.hG();a.dr();g.S(a.element,"ytp-upnext-autoplay-paused")},h6=function(a){a.A&&(a.A.dispose(),a.A=null)},j6=function(a,b){b=void 0===b?!1:b;
var c=g.Y(a.o);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.C.Xb(),a.En(),a.D=new window.Notification("\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435",{body:d.title,icon:d.bd(c)}),a.F=a.O(a.D,"click",a.pS),a.H.start())}h6(a);a.o.fk(!1,b)},sAa=function(a){e6.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.A=new g.W({G:"div",L:"ytp-subscribe-card",N:[{G:"img",L:"ytp-author-image",P:{src:b.profilePicture}},{G:"div",L:"ytp-subscribe-card-right",N:[{G:"div",L:"ytp-author-name",aa:b.author},{G:"div",L:"html5-subscribe-button-container"}]}]});g.N(this,this.A);this.A.ua(this.element);this.B=new g.C_("\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f",null,"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0443",null,!0,
!1,b.Mh,b.subscribed,"trailer-endscreen",null,null,a);g.N(this,this.B);this.B.ua(this.A.g["html5-subscribe-button-container"]);this.hide()},k6=function(a){var b=g.Y(a),c=g.zI||g.bf?{style:"will-change: opacity"}:void 0,d=b.g,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",da:e,P:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},N:[{G:"div",L:"ytp-videowall-still-image",P:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",N:[{G:"span",L:"ytp-videowall-still-info-bg",N:[{G:"span",L:"ytp-videowall-still-info-content",P:c,N:[{G:"span",L:"ytp-videowall-still-info-title",aa:"{{title}}"},{G:"span",
L:"ytp-videowall-still-info-author",aa:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",aa:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{G:"span",L:"ytp-videowall-still-info-duration",aa:"{{duration}}"}]}]}]},{G:"span",da:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],N:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"\u041f\u043b\u0435\u0439\u043b\u0438\u0441\u0442",{G:"span",L:"ytp-videowall-still-listlabel-length",N:[" (",{G:"span",aa:"{{playlist_length}}"},
")"]}]},{G:"span",da:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],N:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0438\u043a\u0441",{G:"span",L:"ytp-videowall-still-listlabel-length",aa:" (50+)"}]}]});this.C=d;this.o=a;this.A=null;this.B=new g.FF(this);g.N(this,this.B);this.U("click",this.F);this.U("keypress",this.H);this.B.O(a,"videodatachange",this.D);g.Y(a).X&&(a=a.app.fa,b=this.element,g.Na(a.g,b),g.Qa(a.g,b),c=String(a.F++),b.setAttribute("data-visual-id",
c),g.Xe(this,(0,g.A)(a.D,a,b)));this.D()},l6=function(a){e6.call(this,a,"videowall-endscreen");
this.K=a;this.F=0;this.B=[];this.H=this.D=this.C=null;this.I=this.R=!1;this.W=new g.FF(this);g.N(this,this.W);this.J=new g.Yt(g.Ea(g.S,this.element,"ytp-show-tiles"),0);g.N(this,this.J);var b=new g.W({G:"button",da:["ytp-button","ytp-endscreen-previous"],P:{"aria-label":"\u041d\u0430\u0437\u0430\u0434"},N:[g.MV()]});g.N(this,b);b.ua(this.element);b.U("click",this.mO,this);this.M=new g.lH({G:"div",L:"ytp-endscreen-content"});g.N(this,this.M);this.M.ua(this.element);b=new g.W({G:"button",da:["ytp-button",
"ytp-endscreen-next"],P:{"aria-label":"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},N:[g.NV()]});g.N(this,b);b.ua(this.element);b.U("click",this.lO,this);this.A=new f6(a);g.N(this,this.A);g.tV(this.o,this.A.element,4);this.hide()},m6=function(a){return g.uV(a.o)&&a.zx()&&!a.H},tAa=function(a,b){return(0,g.I)(b.suggestions,function(b){b=g.vY(b);
g.N(a,b);return b})},n6=function(a){var b=a.ou();
b!=a.R&&(a.R=b,a.o.T("autonavvisibility"))},o6=function(a){g.zV.call(this,a);
this.l=null;this.o=new g.FF(this);g.N(this,this.o);this.A=g.Y(a);uAa(a)?this.l=new l6(this.g):this.A.Ma?this.l=new sAa(this.g):this.l=new e6(this.g);g.N(this,this.l);g.tV(this.g,this.l.element,4);this.FD();this.o.O(a,"videodatachange",this.FD,this);this.o.O(a,"crn_endscreen",this.nM,this);this.o.O(a,"crx_endscreen",this.oM,this)},uAa=function(a){a=g.Y(a);
return a.hd&&!a.Ma};
g.t(e6,g.rH);e6.prototype.create=function(){this.created=!0};
e6.prototype.destroy=function(){this.created=!1};
e6.prototype.zx=function(){return!1};
e6.prototype.ou=function(){return!1};g.t(f6,g.W);g.h=f6.prototype;g.h.En=function(){this.D&&(this.H.stop(),this.Da(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.oC=function(){g.qH(this,g.WU(this.o))};
g.h.pS=function(){window.focus();this.En()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.dr=function(a){a=a||g.Y(this.o).experiments.l("autoplay_time")||1E4;var b=Math.min(g.hG()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.o.Ra()?j6(this,!0):this.A&&this.A.start()};
g.h.zS=function(a){!g.Nd(this.B.element,g.tF(a))&&g.wX(a,this.o)&&j6(this)};
g.h.qQ=function(){g.YU(this.o,!0)};
g.h.PR=function(a){this.o.Ra();this.show();g6(this,a)};
g.h.TE=function(a){this.o.Ra();this.C&&this.C.Xb().videoId==a.Xb().videoId||rAa(this,a)};
g.h.QR=function(){this.o.Ra();h6(this);this.hide()};
g.h.V=function(){h6(this);this.En();g.W.prototype.V.call(this)};g.t(sAa,e6);g.t(k6,g.W);k6.prototype.wk=function(){g.xV(this.o,this.element);var a=this.A.Xb().videoId,b=this.A.getPlaylistId();g.K0(this.o.app,a,this.A.Md,b,void 0,void 0,void 0)};
k6.prototype.F=function(a){g.wX(a,this.o,this.C,this.A.Md||void 0)&&this.wk()};
k6.prototype.H=function(a){switch(a.keyCode){case 13:case 32:g.yF(a)||(this.wk(),g.xF(a))}};
k6.prototype.D=function(){var a=this.o.getVideoData(),b=g.Y(this.o);this.C=a.isDni?!1:b.g};g.t(l6,e6);g.h=l6.prototype;g.h.create=function(){e6.prototype.create.call(this);var a=this.o.getVideoData();a&&(this.C=tAa(this,a),this.D=a);this.Gg();this.W.O(this.o,"appresize",this.Gg);this.W.O(this.o,"onVideoAreaChange",this.Gg);this.W.O(this.o,"videodatachange",this.nO);this.W.O(this.o,"autonavchange",this.nB);this.W.O(this.o,"autonavcancel",this.kO);this.W.O(this.element,"transitionend",this.QT)};
g.h.destroy=function(){g.HF(this.W);g.Ze(this.B);this.B=[];this.C=null;e6.prototype.destroy.call(this);g.lq(this.element,"ytp-show-tiles");this.J.stop()};
g.h.zx=function(){return 1!=this.D.autonavState};
g.h.show=function(){e6.prototype.show.call(this);g.lq(this.element,"ytp-show-tiles");g.Y(this.o).o?g.$t(this.J):this.J.start();(this.I||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.YU(this.o,!1);m6(this)?(n6(this),2==this.D.autonavState?g.Y(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.Fi()?j6(this.A,!0):g6(this.A):3==this.D.autonavState&&i6(this.A)):(g.YU(this.o,!0),n6(this))};
g.h.hide=function(){e6.prototype.hide.call(this);i6(this.A);n6(this)};
g.h.QT=function(a){g.tF(a)==this.element&&this.Gg()};
g.h.Gg=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.lV(this.K,!0),b=g.EH(this.K);b&&(b=b.qd()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,v=b<=f-2&&n>=r*m,D=e<=k-2&&n>=q*m;if((q+1)/r*d/c>c/(q/(r+1)*d)&&D)n-=q*m,e+=2;else if(v)n-=r*m,b+=2;else if(D)n-=q*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.$c(a.width/m||1,1,1.21);n*=g.$c(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.M.element;g.Fh(a,m,n);g.mh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});rAa(this.A,this.C[0]);g.U(this.element,"ytp-endscreen-takeover",m6(this));n6(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&
2>f?0==k&&0==f&&(r=2):r=2),q=g.ad(q+this.F,l),0!=r){v=this.B[c];v||(v=new k6(this.o),this.B[c]=v,a.appendChild(v.element));D=Math.floor(n*k/e);var H=Math.floor(m*f/b),L=Math.floor(n*(k+r)/e)-D-4,T=Math.floor(m*(f+r)/b)-H-4;g.th(v.element,H,D);g.Fh(v.element,T,L);g.mh(v.element,"transitionDelay",(k+f)/20+"s");g.U(v.element,"ytp-videowall-still-mini",1==r);g.U(v.element,"ytp-videowall-still-large",2<r);r=v;q=this.C[q];r.A!=q&&(r.A=q,qAa(r,q,g.Y(r.o),g.jq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":
"mqdefault.jpg"),v=(q=q.Md)&&q.itct)&&(q=r.o,g.Y(q).X&&(q=q.app.fa,r=r.element,D=r.getAttribute("data-visual-id"),g.Na(q.g,r),g.vV(q,"onLogServerVeCreated",{id:D,tracking_params:v})));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.B.length-1;b>=c;b--)e=this.B[b],g.Hd(e.element),g.Ye(e);this.B.length=c}};
g.h.nO=function(){var a=this.o.getVideoData();this.D!=a&&(this.F=0,this.C=tAa(this,a),this.D=a,this.Gg())};
g.h.lO=function(){this.F+=this.B.length;this.Gg()};
g.h.mO=function(){this.F-=this.B.length;this.Gg()};
g.h.rL=function(){return!!this.A.A};
g.h.nB=function(a){1==a?(this.I=!1,this.H=this.D.clientPlaybackNonce,h6(this.A),this.l&&this.Gg()):(this.I=!0,this.l&&m6(this)&&(2==a?g6(this.A):3==a&&i6(this.A)))};
g.h.kO=function(a){if(a){for(a=0;a<this.B.length;a++)g.yV(this.K,this.B[a].element,!0);this.nB(1)}else this.H=null,this.I=!1;this.Gg()};
g.h.ou=function(){return this.l&&m6(this)};g.t(o6,g.zV);g.h=o6.prototype;g.h.OA=function(){var a=this.g.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!uAa(this.g)||b;a=g.SO(a,"ypc_module");var c=g.L0(this.g.app);return b&&!a&&!c};
g.h.NA=function(){return this.l.ou()};
g.h.nL=function(){return this.NA()?this.l.rL():!1};
g.h.V=function(){g.rV(this.g,"endscreen");g.zV.prototype.V.call(this)};
g.h.load=function(){g.zV.prototype.load.call(this);this.l.show()};
g.h.unload=function(){g.zV.prototype.unload.call(this);this.l.hide();this.l.destroy()};
g.h.nM=function(a){this.OA()&&(this.l.created||this.l.create(),"load"==a.getId()&&this.load())};
g.h.oM=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.FD=function(){g.rV(this.g,"endscreen");var a=Math.max(1E3*(this.g.getVideoData().lengthSeconds-10),0);a=new g.rQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.N(this,a);var b=new g.rQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.N(this,b);g.oV(this.g,[a,b])};g.pY.endscreen=o6;})(_yt_player);
